10 REM A SHORT PROGRAM TO CALCULATE FACTORIAL OF
20 REM SUPPLIED NUMBER N
30 INPUT "Please provide N: ": N
40 OUTPUT = 1
50 FOR I = 1 TO N
60 OUTPUT = OUTPUT * I
70 NEXT I
80 PRINT "Factorial of N is ", OUTPUT
