# TODO: Remove `|| true` from lines and try to get the tests to pass.
# TODO: Remove `flake8 --ignore` items one-by-one and try to get the tests to pass.
name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip
      - run: pip install bandit codespell flake8 mypy pytest
      - run: bandit --recursive --skip B307,B311 .  # random library and eval()
      - run: codespell --ignore-words-list="ans,fro,hel"
      - run: flake8 --ignore=E111,E114,E116,E117,E127,E128,E221,E225,E226,E231,E261,E265,E302,E303,E305,E711,E722,W292,W503,W504
                    --count --max-complexity=88 --max-line-length=136 --show-source --statistics .
      - run: mkdir --parents --verbose .mypy_cache
      - run: mypy --ignore-missing-imports --install-types --non-interactive .
      - run: pytest --doctest-modules .
